name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # Make sure 'dist' is the directory where the output goes
          outputs: dist/github-contribution-grid-snake.svg 

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output # The branch where the SVG will be published
          build_dir: dist # The directory containing the SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
